---
title       : Investment - Delta Hedge Fund vs Savings Account
subtitle    : Market vs Best Available Bank Rate
author      : B.A. McDougall
job         : NSCI Consulting
framework   : io2012     # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax, bootstrap]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Definitions from Finance
* **Stock** An asset representing partial ownership of a publicly traded firm.
* **American Option** Right to buy (long) or sell (short) an asset at strike price $S_k$ at any time until maturity for a premium.
* **European Option** Right to buy (long) or sell (short) an asset at strike price $S_k$ at maturity for a premium.
* **Call Option** Option to buy an asset at strike price $S_k$ at maturity for a premium.
* **Put Option** Option to sell an asset at strike price $S_k$ at maturity for a premium.

## Savings Account: Limit of continuous compounding
* $r =$ risk free interest rate; $PV =$ Present Value of Money; $FV =$ Future Value of Money
* With annual compounding, $FV_1 = PV (1 + r) \Longrightarrow FV_t = PV(1+\frac{r}{n})^{nt}$
* In limit of decreasing time intervals, $FV_t = \lim_{n\to\infty} PV(1+\frac{r}{n})^{\frac{n}{r} rt} = PV e^{rt}$

---
## Portfolio Management

### Generate Risk Neutral Valued (RNV) Portfolio using [Binary Tree Model](https://en.wikipedia.org/wiki/Binomial_options_pricing_model)
* Purchasing $\Delta$ shares of stock at price $S_o$, and short a call option on same stock with value $f$
* Value of RNV portfolio is same whether stock price goes up or down; therefore, $(\Delta S_o) u - f_u = (\Delta S_o) d - f_d$.  $u$ is multiplier for increase; $d$ is multiplier for decrease.

### $\Delta$ Hedge for RNV Portfolio
* From equality, $\Delta$ required for creating a RNV Portfolio is $\Delta = \frac{f_u - f_d}{S_o (u-d)}$
* PV of RNV is discounted FV $\Longrightarrow (\Delta S_o)  - f = e^{-r t} \left[ (\Delta S_o) u - f_u \right]$
* Solving for f estimates PV of call option $\Longrightarrow f = e^{-r t} \left[ p f_u + (1 - p) f_d \right]$
where
<div class="centered">
\begin{equation}
p = \frac{e^{r t} - d}{u - d}
\end{equation}
</div>

* **NOTE**:  f is discounted expectation value of option's FV against a binomial density (*coin flip*)

---
## Portfolio Management (continued)
* For stochastic processes, variance is proportional to $\Delta t$, so
<div class="centered">
\begin{equation}
\sigma^2 \Delta t = \langle S(t)^2 \rangle - \langle S(t) \rangle ^2
\end{equation}
</div>
<div class="centered">
\begin{equation}
\sigma^2 \Delta t = \left[ p u^2 + (1-p) d^2 \right] - \left[ \left( p u + (1-p) d \right)^2 \right]
\end{equation}
</div>
<div class="centered">
\begin{equation}
\sigma^2 \Delta t = (u + d) e^{\mu t} - du - e^{2 \mu t}
\end{equation}
</div>

* Using a Taylor Expansion, one validates a solution for u & d is $u = e^{\sigma \sqrt{\Delta t}}$ & $d = e^{- \sigma \sqrt{\Delta t}}$
* Summarizing:  (1) FV of RNV Portfolio is $\left[(\Delta S_o)  - f\right]e^{\mu t}$ which is of same form as FV of Savings account; (2) The relationship between $f$ and $S_o$ is fully determined.

## Pricing a Stock
* Two assumptions: (1) during a small time interval, a random contribution to the differential of stock price is $\epsilon \sqrt(\Delta t)$ where $\epsilon$ is a standard normal distribution; (2) Values of $\epsilon \sqrt(\Delta t)$ from any two time intervals $\Delta t$ are mutually independent.

---
## Time Dependence of $S$

* The differential of stock price is $d S = \mu S d t + \sigma S \epsilon \sqrt{dt}$. Neglecting volatility, $S(t) = S_o e^{\mu t}$.

* Solving numerically, $\Delta S = \mu S \Delta t + \sigma S \epsilon \sqrt{\Delta t}$, so $S_{i + 1} = S_i + \mu S_i \Delta t + \sigma S_i \epsilon \sqrt{\Delta t}$

* Numerical simulation and actual stock price of Google (Dates:  1/2/2015 - 6/12/2015).  Plot also shows savings account (best interest $r=1.25\%$) & a $\Delta$ Hedge with Google stock (market rate $\mu= 6.28 \%$ &
$ \sigma = $ \$41.)

```{r stockPricing, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, fig.height=3, fig.width=12, fig.show='animate'}
################################################################################
##
## This section is for comparing Google Stock Price with Wiener Pricing of Stock
##  For comparison, bank savings is shown.  Import Google price history. 
##
mu <- (547.47 - 532.60) / 532.60 # ~0.15 annualized rate of return from
# https://www.stock-analysis-on.net/NASDAQ/Company/Google-Inc/Valuation/Ratios
mu_daily <- mu / 112

finGrowthTbl <- tbl_df(
    read.csv2("googl.csv", sep = ",", stringsAsFactors = FALSE, na.strings = "NA",
              header = TRUE, #colClasses = c("character", "numeric", "numeric", "numeric", "numeric", "numeric")
              )
    )   %>%
    select(
        Date, Open, High, Low, Close, Volume
        ) %>%
    mutate(
        dateClose = ymd_hms( paste( dmy(Date), hms(c("16:00:00") )), tz = "America/New_York"),
        Open = as.numeric(Open), High = as.numeric(High), Low = as.numeric(Low), Close = as.numeric(Close),
        Volume = as.numeric(Volume)
        ) %>%
    select(
        dateClose,
        Date, Open, High, Low, Close, Volume      
        )  %>%
    filter(
        dateClose > mdy("01/01/2015") & dateClose < mdy("06/30/2015")
        ) %>%
    mutate(
        ydayNum = yday(dateClose),
        days = as.period( (dateClose - ymd_hms("2015-01-02 16:00:00", tz = "America/New_York") ) ) %/% days(1)        
        )%>%
    arrange(ydayNum)%>%
    mutate(
        Savings = (532.60 * (1 + aprDay)**(days)),
        Contin = (532.60 * exp( aprDay * days) ),
        goog_W = 0,
        goog_H = (532.60 * exp( mu_daily * days) )
        )%>%
    select(
        dateClose, days,
        Open, High, Low, Close, goog_W, goog_H, Savings
        )
##
################################################################################
##
## This section for determining volatility in Google Stock between 2015-01-02
##  and 2015-06-12, which is 112 trading days and estimate Stock price with Wiener model
##
sd_googl <- sd(finGrowthTbl$Close) # for 112 trading days
sd_googlDly <-  sd_googl / 112

goog_W <- vector("numeric", length = 112)
goog_W[1] <- 532.60


for(j in 1:30) {
    for(i in 2:112) {
        #     set.seed(314159)
        goog_W[i] <- goog_W[i-1] * (1 + mu_daily * (1/365) + sd_googlDly * rnorm(1) * sqrt(1/365)) 
        }
    finGrowthTbl$goog_W <- goog_W
    
    mnyPlt <- ggplot() + scale_colour_hue("Instrument") + scale_y_continuous(limits = c(450, 650))
    mnyPlt <- mnyPlt + geom_line(data=finGrowthTbl, aes(x = dateClose, y = Close, color="GOOGL"))
    mnyPlt <- mnyPlt + geom_line(data=finGrowthTbl, aes(x = dateClose, y = goog_H, color = "goog_H"))
    mnyPlt <- mnyPlt + geom_line(data=finGrowthTbl, aes(x = dateClose, y = Savings, color = "Savings"))
    mnyPlt <- mnyPlt + labs(x = "Date", y = "Amount [$]", title = "Money:  Time Value")
    mnyPlt <- mnyPlt + geom_line(data=finGrowthTbl, aes(x = dateClose, y = goog_W, color="goog_W"))
    print(mnyPlt)
    }
```
* Animation demonstrates stochastic nature of stock pricing.  Each simulation presents a valid solution.
